# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\mubu.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubu(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/login")
            .get("https://${host}/login")
            .with_headers(
                **{
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Cookie": "_ga=GA1.2.728977736.1599662095; data_unique_id=d1e44655-5e65-4720-912e-9aece6f1369f; mubu_inner=1; csrf_token=892e56e3-15a3-46c7-a46d-56476a8e1f69; s_v_web_id=kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL; reg_entrance=https%3A%2F%2F${host}%2Flist; _gid=GA1.2.1134841487.1600173818; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1599662193,1599875248,1600173818; language=en-US; country=US; reg_prepareId=17491d234a5-17491d234a0-4578-acd5-0429ec3e25cd; reg_focusId=4f90fb7c-cef8-4578-acd5-17491d239a9; SESSION=0ae21984-7c22-4e0d-b12e-e03790fe6ba3; _gat=1; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1600174423; SLARDAR_WEB_ID=2f2dda9a-29b5-4a04-825a-a23c6ba6d3a4",
                    "Host": "${host}",
                    "Referer": "https://${host}/",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-User": "?1",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1600174423",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1599662193,1599875248,1600173818",
                    "SESSION": "0ae21984-7c22-4e0d-b12e-e03790fe6ba3",
                    "SLARDAR_WEB_ID": "2f2dda9a-29b5-4a04-825a-a23c6ba6d3a4",
                    "_ga": "GA1.2.728977736.1599662095",
                    "_gat": "1",
                    "_gid": "GA1.2.1134841487.1600173818",
                    "country": "US",
                    "csrf_token": "892e56e3-15a3-46c7-a46d-56476a8e1f69",
                    "data_unique_id": "d1e44655-5e65-4720-912e-9aece6f1369f",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "reg_focusId": "4f90fb7c-cef8-4578-acd5-17491d239a9",
                    "reg_prepareId": "17491d234a5-17491d234a0-4578-acd5-0429ec3e25cd",
                    "s_v_web_id": "kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html;charset=UTF-8")
        ),
        Step(
            RunRequest("/login/password")
            .get("https://${host}/login/password")
            .with_headers(
                **{
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Cookie": "_ga=GA1.2.728977736.1599662095; data_unique_id=d1e44655-5e65-4720-912e-9aece6f1369f; mubu_inner=1; csrf_token=892e56e3-15a3-46c7-a46d-56476a8e1f69; s_v_web_id=kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL; reg_entrance=https%3A%2F%2F${host}%2Flist; _gid=GA1.2.1134841487.1600173818; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1599662193,1599875248,1600173818; language=en-US; country=US; SESSION=0ae21984-7c22-4e0d-b12e-e03790fe6ba3; _gat=1; SLARDAR_WEB_ID=90b0e644-0a9e-4112-ac4c-7a313d54f9bd; reg_prepareId=17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1600174436; reg_focusId=54c7d421-47a5-4c16-a29d-17491d430a9",
                    "Host": "${host}",
                    "Referer": "https://${host}/login",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-User": "?1",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1600174436",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1599662193,1599875248,1600173818",
                    "SESSION": "0ae21984-7c22-4e0d-b12e-e03790fe6ba3",
                    "SLARDAR_WEB_ID": "90b0e644-0a9e-4112-ac4c-7a313d54f9bd",
                    "_ga": "GA1.2.728977736.1599662095",
                    "_gat": "1",
                    "_gid": "GA1.2.1134841487.1600173818",
                    "country": "US",
                    "csrf_token": "892e56e3-15a3-46c7-a46d-56476a8e1f69",
                    "data_unique_id": "d1e44655-5e65-4720-912e-9aece6f1369f",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "reg_focusId": "54c7d421-47a5-4c16-a29d-17491d430a9",
                    "reg_prepareId": "17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a",
                    "s_v_web_id": "kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html;charset=UTF-8")
        ),
        Step(
            RunRequest("/api/login/submit")
            .post("https://${host}/api/login/submit")
            .with_headers(
                **{
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "52",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Cookie": "_ga=GA1.2.728977736.1599662095; data_unique_id=d1e44655-5e65-4720-912e-9aece6f1369f; mubu_inner=1; csrf_token=892e56e3-15a3-46c7-a46d-56476a8e1f69; s_v_web_id=kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL; reg_entrance=https%3A%2F%2F${host}%2Flist; _gid=GA1.2.1134841487.1600173818; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1599662193,1599875248,1600173818; language=en-US; country=US; SESSION=0ae21984-7c22-4e0d-b12e-e03790fe6ba3; _gat=1; reg_prepareId=17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a; reg_focusId=54c7d421-47a5-4c16-a29d-17491d430a9; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1600174437; SLARDAR_WEB_ID=701da187-6f92-4859-b639-1bbb446e3b30",
                    "Host": "${host}",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/login/password",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1600174437",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1599662193,1599875248,1600173818",
                    "SESSION": "0ae21984-7c22-4e0d-b12e-e03790fe6ba3",
                    "SLARDAR_WEB_ID": "701da187-6f92-4859-b639-1bbb446e3b30",
                    "_ga": "GA1.2.728977736.1599662095",
                    "_gat": "1",
                    "_gid": "GA1.2.1134841487.1600173818",
                    "country": "US",
                    "csrf_token": "892e56e3-15a3-46c7-a46d-56476a8e1f69",
                    "data_unique_id": "d1e44655-5e65-4720-912e-9aece6f1369f",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "reg_focusId": "54c7d421-47a5-4c16-a29d-17491d430a9",
                    "reg_prepareId": "17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a",
                    "s_v_web_id": "kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL",
                }
            )
            .with_data(
                {"password": "xiaoniuer11", "phone": "18628359732", "remember": "true"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/list")
            .get("https://${host}/list")
            .with_headers(
                **{
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Cookie": "_ga=GA1.2.728977736.1599662095; data_unique_id=d1e44655-5e65-4720-912e-9aece6f1369f; mubu_inner=1; csrf_token=892e56e3-15a3-46c7-a46d-56476a8e1f69; s_v_web_id=kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL; reg_entrance=https%3A%2F%2F${host}%2Flist; _gid=GA1.2.1134841487.1600173818; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1599662193,1599875248,1600173818; language=en-US; country=US; SESSION=0ae21984-7c22-4e0d-b12e-e03790fe6ba3; _gat=1; reg_prepareId=17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a; reg_focusId=54c7d421-47a5-4c16-a29d-17491d430a9; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1600174437; SLARDAR_WEB_ID=701da187-6f92-4859-b639-1bbb446e3b30; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A; user_persistence=bef4f285-6853-4476-bf6e-74cd85552cfa",
                    "Host": "${host}",
                    "Referer": "https://${host}/login/password",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-User": "?1",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1600174437",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1599662193,1599875248,1600173818",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "SESSION": "0ae21984-7c22-4e0d-b12e-e03790fe6ba3",
                    "SLARDAR_WEB_ID": "701da187-6f92-4859-b639-1bbb446e3b30",
                    "_ga": "GA1.2.728977736.1599662095",
                    "_gat": "1",
                    "_gid": "GA1.2.1134841487.1600173818",
                    "country": "US",
                    "csrf_token": "892e56e3-15a3-46c7-a46d-56476a8e1f69",
                    "data_unique_id": "d1e44655-5e65-4720-912e-9aece6f1369f",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "reg_focusId": "54c7d421-47a5-4c16-a29d-17491d430a9",
                    "reg_prepareId": "17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a",
                    "s_v_web_id": "kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL",
                    "user_persistence": "bef4f285-6853-4476-bf6e-74cd85552cfa",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html;charset=UTF-8")
        ),
        Step(
            RunRequest("/api/list/tip_new_update")
            .post("https://${host}/api/list/tip_new_update")
            .with_headers(
                **{
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Cookie": "_ga=GA1.2.728977736.1599662095; data_unique_id=d1e44655-5e65-4720-912e-9aece6f1369f; mubu_inner=1; csrf_token=892e56e3-15a3-46c7-a46d-56476a8e1f69; s_v_web_id=kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL; reg_entrance=https%3A%2F%2F${host}%2Flist; _gid=GA1.2.1134841487.1600173818; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1599662193,1599875248,1600173818; language=en-US; country=US; SESSION=0ae21984-7c22-4e0d-b12e-e03790fe6ba3; _gat=1; reg_prepareId=17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a; reg_focusId=54c7d421-47a5-4c16-a29d-17491d430a9; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1600174437; SLARDAR_WEB_ID=701da187-6f92-4859-b639-1bbb446e3b30; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A; user_persistence=bef4f285-6853-4476-bf6e-74cd85552cfa",
                    "Host": "${host}",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/list",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1600174437",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1599662193,1599875248,1600173818",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "SESSION": "0ae21984-7c22-4e0d-b12e-e03790fe6ba3",
                    "SLARDAR_WEB_ID": "701da187-6f92-4859-b639-1bbb446e3b30",
                    "_ga": "GA1.2.728977736.1599662095",
                    "_gat": "1",
                    "_gid": "GA1.2.1134841487.1600173818",
                    "country": "US",
                    "csrf_token": "892e56e3-15a3-46c7-a46d-56476a8e1f69",
                    "data_unique_id": "d1e44655-5e65-4720-912e-9aece6f1369f",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "reg_focusId": "54c7d421-47a5-4c16-a29d-17491d430a9",
                    "reg_prepareId": "17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a",
                    "s_v_web_id": "kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL",
                    "user_persistence": "bef4f285-6853-4476-bf6e-74cd85552cfa",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/get")
            .post("https://${host}/api/list/get")
            .with_headers(
                **{
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "38",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Cookie": "_ga=GA1.2.728977736.1599662095; data_unique_id=d1e44655-5e65-4720-912e-9aece6f1369f; mubu_inner=1; csrf_token=892e56e3-15a3-46c7-a46d-56476a8e1f69; s_v_web_id=kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL; reg_entrance=https%3A%2F%2F${host}%2Flist; _gid=GA1.2.1134841487.1600173818; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1599662193,1599875248,1600173818; language=en-US; country=US; SESSION=0ae21984-7c22-4e0d-b12e-e03790fe6ba3; _gat=1; reg_prepareId=17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a; reg_focusId=54c7d421-47a5-4c16-a29d-17491d430a9; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1600174437; SLARDAR_WEB_ID=701da187-6f92-4859-b639-1bbb446e3b30; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A; user_persistence=bef4f285-6853-4476-bf6e-74cd85552cfa",
                    "Host": "${host}",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/list",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1600174437",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1599662193,1599875248,1600173818",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "SESSION": "0ae21984-7c22-4e0d-b12e-e03790fe6ba3",
                    "SLARDAR_WEB_ID": "701da187-6f92-4859-b639-1bbb446e3b30",
                    "_ga": "GA1.2.728977736.1599662095",
                    "_gat": "1",
                    "_gid": "GA1.2.1134841487.1600173818",
                    "country": "US",
                    "csrf_token": "892e56e3-15a3-46c7-a46d-56476a8e1f69",
                    "data_unique_id": "d1e44655-5e65-4720-912e-9aece6f1369f",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "reg_focusId": "54c7d421-47a5-4c16-a29d-17491d430a9",
                    "reg_prepareId": "17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a",
                    "s_v_web_id": "kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL",
                    "user_persistence": "bef4f285-6853-4476-bf6e-74cd85552cfa",
                }
            )
            .with_data({"folderId": "0", "keywords": "", "sort": "time", "source": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/message/get_message_unread")
            .post("https://${host}/api/message/get_message_unread")
            .with_headers(
                **{
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Cookie": "_ga=GA1.2.728977736.1599662095; data_unique_id=d1e44655-5e65-4720-912e-9aece6f1369f; mubu_inner=1; csrf_token=892e56e3-15a3-46c7-a46d-56476a8e1f69; s_v_web_id=kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL; reg_entrance=https%3A%2F%2F${host}%2Flist; _gid=GA1.2.1134841487.1600173818; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1599662193,1599875248,1600173818; language=en-US; country=US; SESSION=0ae21984-7c22-4e0d-b12e-e03790fe6ba3; _gat=1; reg_prepareId=17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a; reg_focusId=54c7d421-47a5-4c16-a29d-17491d430a9; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1600174437; SLARDAR_WEB_ID=701da187-6f92-4859-b639-1bbb446e3b30; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A; user_persistence=bef4f285-6853-4476-bf6e-74cd85552cfa",
                    "Host": "${host}",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/list",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1600174437",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1599662193,1599875248,1600173818",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "SESSION": "0ae21984-7c22-4e0d-b12e-e03790fe6ba3",
                    "SLARDAR_WEB_ID": "701da187-6f92-4859-b639-1bbb446e3b30",
                    "_ga": "GA1.2.728977736.1599662095",
                    "_gat": "1",
                    "_gid": "GA1.2.1134841487.1600173818",
                    "country": "US",
                    "csrf_token": "892e56e3-15a3-46c7-a46d-56476a8e1f69",
                    "data_unique_id": "d1e44655-5e65-4720-912e-9aece6f1369f",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "reg_focusId": "54c7d421-47a5-4c16-a29d-17491d430a9",
                    "reg_prepareId": "17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a",
                    "s_v_web_id": "kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL",
                    "user_persistence": "bef4f285-6853-4476-bf6e-74cd85552cfa",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/create_doc")
            .post("https://${host}/api/list/create_doc")
            .with_headers(
                **{
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "17",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Cookie": "_ga=GA1.2.728977736.1599662095; data_unique_id=d1e44655-5e65-4720-912e-9aece6f1369f; mubu_inner=1; csrf_token=892e56e3-15a3-46c7-a46d-56476a8e1f69; s_v_web_id=kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL; reg_entrance=https%3A%2F%2F${host}%2Flist; _gid=GA1.2.1134841487.1600173818; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1599662193,1599875248,1600173818; language=en-US; country=US; SESSION=0ae21984-7c22-4e0d-b12e-e03790fe6ba3; _gat=1; reg_prepareId=17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a; reg_focusId=54c7d421-47a5-4c16-a29d-17491d430a9; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A; user_persistence=bef4f285-6853-4476-bf6e-74cd85552cfa; SLARDAR_WEB_ID=ac53b5e7-5262-46f5-9804-4f108467b185; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1600174444",
                    "Host": "${host}",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/list",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1600174444",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1599662193,1599875248,1600173818",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "SESSION": "0ae21984-7c22-4e0d-b12e-e03790fe6ba3",
                    "SLARDAR_WEB_ID": "ac53b5e7-5262-46f5-9804-4f108467b185",
                    "_ga": "GA1.2.728977736.1599662095",
                    "_gat": "1",
                    "_gid": "GA1.2.1134841487.1600173818",
                    "country": "US",
                    "csrf_token": "892e56e3-15a3-46c7-a46d-56476a8e1f69",
                    "data_unique_id": "d1e44655-5e65-4720-912e-9aece6f1369f",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "reg_focusId": "54c7d421-47a5-4c16-a29d-17491d430a9",
                    "reg_prepareId": "17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a",
                    "s_v_web_id": "kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL",
                    "user_persistence": "bef4f285-6853-4476-bf6e-74cd85552cfa",
                }
            )
            .with_data({"folderId": "0", "type": "0"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/doc${docId}")
            .get("https://${host}/doc${docId}")
            .with_headers(
                **{
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Cookie": "_ga=GA1.2.728977736.1599662095; data_unique_id=d1e44655-5e65-4720-912e-9aece6f1369f; mubu_inner=1; csrf_token=892e56e3-15a3-46c7-a46d-56476a8e1f69; s_v_web_id=kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL; reg_entrance=https%3A%2F%2F${host}%2Flist; _gid=GA1.2.1134841487.1600173818; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1599662193,1599875248,1600173818; language=en-US; country=US; SESSION=0ae21984-7c22-4e0d-b12e-e03790fe6ba3; _gat=1; reg_prepareId=17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a; reg_focusId=54c7d421-47a5-4c16-a29d-17491d430a9; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A; user_persistence=bef4f285-6853-4476-bf6e-74cd85552cfa; SLARDAR_WEB_ID=ac53b5e7-5262-46f5-9804-4f108467b185; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1600174444",
                    "Host": "${host}",
                    "Referer": "https://${host}/list",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-User": "?1",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1600174444",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1599662193,1599875248,1600173818",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "SESSION": "0ae21984-7c22-4e0d-b12e-e03790fe6ba3",
                    "SLARDAR_WEB_ID": "ac53b5e7-5262-46f5-9804-4f108467b185",
                    "_ga": "GA1.2.728977736.1599662095",
                    "_gat": "1",
                    "_gid": "GA1.2.1134841487.1600173818",
                    "country": "US",
                    "csrf_token": "892e56e3-15a3-46c7-a46d-56476a8e1f69",
                    "data_unique_id": "d1e44655-5e65-4720-912e-9aece6f1369f",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "reg_focusId": "54c7d421-47a5-4c16-a29d-17491d430a9",
                    "reg_prepareId": "17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a",
                    "s_v_web_id": "kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL",
                    "user_persistence": "bef4f285-6853-4476-bf6e-74cd85552cfa",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html; charset=utf-8")
        ),
        Step(
            RunRequest("/v3/api/user/current_user")
            .post("https://api2.${host}/v3/api/user/current_user")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Host": "api2.${host}",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/doc${docId}",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "x-request-id": "22cd5225-23de-4756-a919-1cef09840460",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/get")
            .post("https://api2.${host}/v3/api/document/get")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "22",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.${host}",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/doc${docId}",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "x-request-id": "8e47ceec-d3a7-4470-93f0-968744bdeb3c",
                }
            )
            .with_json({"docId": "${docId}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .post("https://api2.${host}/v3/api/user/current_level")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "28",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.${host}",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/doc${docId}",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "x-request-id": "b907f3f7-1521-4bb0-a9f0-88cef67761ba",
                }
            )
            .with_json({"document_id": "${docId}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.${host}/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Host": "api2.${host}",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/doc${docId}",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "x-request-id": "a732f7e5-4619-4c2d-b88d-3d5c8b82a127",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_invite_count")
            .get("https://api2.${host}/v3/api/user/get_invite_count")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Host": "api2.${host}",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/doc${docId}",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "x-request-id": "44ebed27-56a8-4691-ad1a-ef78452605ed",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("https://api2.${host}/v3/api/colla/register")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Host": "api2.${host}",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/doc${docId}",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "x-request-id": "e50c331c-4c5b-439f-953b-e2b3004099ba",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .options("https://api2.${host}/v3/api/colla/members")
            .with_params(**{"documentId": "${docId}", "memberId": "3346636299773350"})
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Access-Control-Request-Headers": "data-unique-id,jwt-token,request-id,x-request-id",
                    "Access-Control-Request-Method": "GET",
                    "Connection": "keep-alive",
                    "Host": "api2.${host}",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/doc${docId}",
                    "Sec-Fetch-Mode": "no-cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/octet-stream")
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .get("https://api2.${host}/v3/api/colla/members")
            .with_params(**{"documentId": "${docId}", "memberId": "3346636299773350"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Host": "api2.${host}",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/doc${docId}",
                    "Request-Id": "members:3346636299773350:1600174447903",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "x-request-id": "93ad824f-c6f2-4a9d-86ff-963870a83338",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "458",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.${host}",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "Member-Id": "3346636299773350",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/doc${docId}",
                    "Request-Id": "MESSAGE:9010608:3346636299773350:3",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "x-request-id": "38b84f58-554d-450d-bd7c-9bd1e1d027f7",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "1.0.0.401",
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {"name": "nameChanged", "original": "", "title": "1"},
                                {"name": "nameChanged", "original": "1", "title": "11"},
                                {
                                    "name": "nameChanged",
                                    "original": "11",
                                    "title": "111",
                                },
                            ],
                            "documentId": "${docId}",
                            "type": "CHANGE",
                            "version": 0,
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 3,
                    "requestId": "MESSAGE:9010608:3346636299773350:3",
                    "token": "${docId}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "458",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.${host}",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "Member-Id": "3346636299773350",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/doc${docId}",
                    "Request-Id": "MESSAGE:9010608:3346636299773350:5",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "x-request-id": "1b59585d-ee51-4ff1-8064-8aa1e271e12f",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "1.0.0.401",
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "created": [
                                        {
                                            "index": 0,
                                            "node": {
                                                "children": [],
                                                "id": "PDBY8JgcrR",
                                                "modified": 1600174449800,
                                                "text": "",
                                            },
                                            "parentId": None,
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                    "name": "create",
                                }
                            ],
                            "documentId": "${docId}",
                            "type": "CHANGE",
                            "version": 1,
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 5,
                    "requestId": "MESSAGE:9010608:3346636299773350:5",
                    "token": "${docId}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "503",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.${host}",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "Member-Id": "3346636299773350",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/doc${docId}",
                    "Request-Id": "MESSAGE:9010608:3346636299773350:7",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "x-request-id": "60b103bd-26ff-43ca-8188-c1edb5576c42",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "1.0.0.401",
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "original": {
                                                "id": "PDBY8JgcrR",
                                                "modified": 1600174449800,
                                                "text": "",
                                            },
                                            "path": ["nodes", 0],
                                            "updated": {
                                                "id": "PDBY8JgcrR",
                                                "modified": 1600174450662,
                                                "text": "<span>000</span>",
                                            },
                                        }
                                    ],
                                }
                            ],
                            "documentId": "${docId}",
                            "type": "CHANGE",
                            "version": 2,
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 7,
                    "requestId": "MESSAGE:9010608:3346636299773350:7",
                    "token": "${docId}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "458",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.${host}",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "Member-Id": "3346636299773350",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/doc${docId}",
                    "Request-Id": "MESSAGE:9010608:3346636299773350:9",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "x-request-id": "52cdbe50-f4f6-49b3-8a08-0ea9fa78d9ad",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "1.0.0.401",
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "created": [
                                        {
                                            "index": 1,
                                            "node": {
                                                "children": [],
                                                "id": "8j6zo98Fje",
                                                "modified": 1600174451479,
                                                "text": "",
                                            },
                                            "parentId": None,
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                    "name": "create",
                                }
                            ],
                            "documentId": "${docId}",
                            "type": "CHANGE",
                            "version": 3,
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 9,
                    "requestId": "MESSAGE:9010608:3346636299773350:9",
                    "token": "${docId}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "505",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.${host}",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "Member-Id": "3346636299773350",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/doc${docId}",
                    "Request-Id": "MESSAGE:9010608:3346636299773350:11",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "x-request-id": "f6415297-2a53-4174-9182-8edbc2dcf0a6",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "1.0.0.401",
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "original": {
                                                "id": "8j6zo98Fje",
                                                "modified": 1600174451479,
                                                "text": "",
                                            },
                                            "path": ["nodes", 1],
                                            "updated": {
                                                "id": "8j6zo98Fje",
                                                "modified": 1600174452445,
                                                "text": "<span>111</span>",
                                            },
                                        }
                                    ],
                                }
                            ],
                            "documentId": "${docId}",
                            "type": "CHANGE",
                            "version": 4,
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 11,
                    "requestId": "MESSAGE:9010608:3346636299773350:11",
                    "token": "${docId}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "228",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.${host}",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "Member-Id": "3346636299773350",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/doc${docId}",
                    "Request-Id": "MESSAGE:9010608:3346636299773350:14",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "x-request-id": "27f1687c-f2b0-47cc-b9d7-ad7a5ca7d505",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "1.0.0.401",
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "platform": "web",
                    },
                    "data": {},
                    "engineType": "MUBU",
                    "messageType": "UNWATCH",
                    "reqId": 14,
                    "requestId": "MESSAGE:9010608:3346636299773350:14",
                    "token": "${docId}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/list")
            .get("https://${host}/list")
            .with_headers(
                **{
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Cookie": "_ga=GA1.2.728977736.1599662095; data_unique_id=d1e44655-5e65-4720-912e-9aece6f1369f; mubu_inner=1; csrf_token=892e56e3-15a3-46c7-a46d-56476a8e1f69; s_v_web_id=kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL; reg_entrance=https%3A%2F%2F${host}%2Flist; _gid=GA1.2.1134841487.1600173818; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1599662193,1599875248,1600173818; language=en-US; country=US; SESSION=0ae21984-7c22-4e0d-b12e-e03790fe6ba3; _gat=1; reg_prepareId=17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a; reg_focusId=54c7d421-47a5-4c16-a29d-17491d430a9; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A; user_persistence=bef4f285-6853-4476-bf6e-74cd85552cfa; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1600174444; data-unique-id=8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e; _gat_UA-77727571-3=1; SLARDAR_WEB_ID=09080808-9537-47ce-9745-021db03b845f",
                    "Host": "${host}",
                    "Referer": "https://${host}/doc${docId}",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-User": "?1",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1600174444",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1599662193,1599875248,1600173818",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "SESSION": "0ae21984-7c22-4e0d-b12e-e03790fe6ba3",
                    "SLARDAR_WEB_ID": "09080808-9537-47ce-9745-021db03b845f",
                    "_ga": "GA1.2.728977736.1599662095",
                    "_gat": "1",
                    "_gat_UA-77727571-3": "1",
                    "_gid": "GA1.2.1134841487.1600173818",
                    "country": "US",
                    "csrf_token": "892e56e3-15a3-46c7-a46d-56476a8e1f69",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "data_unique_id": "d1e44655-5e65-4720-912e-9aece6f1369f",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "reg_focusId": "54c7d421-47a5-4c16-a29d-17491d430a9",
                    "reg_prepareId": "17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a",
                    "s_v_web_id": "kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL",
                    "user_persistence": "bef4f285-6853-4476-bf6e-74cd85552cfa",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html;charset=UTF-8")
        ),
        Step(
            RunRequest("/api/list/tip_new_update")
            .post("https://${host}/api/list/tip_new_update")
            .with_headers(
                **{
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Cookie": "_ga=GA1.2.728977736.1599662095; data_unique_id=d1e44655-5e65-4720-912e-9aece6f1369f; mubu_inner=1; csrf_token=892e56e3-15a3-46c7-a46d-56476a8e1f69; s_v_web_id=kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL; reg_entrance=https%3A%2F%2F${host}%2Flist; _gid=GA1.2.1134841487.1600173818; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1599662193,1599875248,1600173818; language=en-US; country=US; SESSION=0ae21984-7c22-4e0d-b12e-e03790fe6ba3; _gat=1; reg_prepareId=17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a; reg_focusId=54c7d421-47a5-4c16-a29d-17491d430a9; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A; user_persistence=bef4f285-6853-4476-bf6e-74cd85552cfa; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1600174444; data-unique-id=8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e; _gat_UA-77727571-3=1; SLARDAR_WEB_ID=09080808-9537-47ce-9745-021db03b845f",
                    "Host": "${host}",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/list",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1600174444",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1599662193,1599875248,1600173818",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "SESSION": "0ae21984-7c22-4e0d-b12e-e03790fe6ba3",
                    "SLARDAR_WEB_ID": "09080808-9537-47ce-9745-021db03b845f",
                    "_ga": "GA1.2.728977736.1599662095",
                    "_gat": "1",
                    "_gat_UA-77727571-3": "1",
                    "_gid": "GA1.2.1134841487.1600173818",
                    "country": "US",
                    "csrf_token": "892e56e3-15a3-46c7-a46d-56476a8e1f69",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "data_unique_id": "d1e44655-5e65-4720-912e-9aece6f1369f",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "reg_focusId": "54c7d421-47a5-4c16-a29d-17491d430a9",
                    "reg_prepareId": "17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a",
                    "s_v_web_id": "kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL",
                    "user_persistence": "bef4f285-6853-4476-bf6e-74cd85552cfa",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/get")
            .post("https://${host}/api/list/get")
            .with_headers(
                **{
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "38",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Cookie": "_ga=GA1.2.728977736.1599662095; data_unique_id=d1e44655-5e65-4720-912e-9aece6f1369f; mubu_inner=1; csrf_token=892e56e3-15a3-46c7-a46d-56476a8e1f69; s_v_web_id=kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL; reg_entrance=https%3A%2F%2F${host}%2Flist; _gid=GA1.2.1134841487.1600173818; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1599662193,1599875248,1600173818; language=en-US; country=US; SESSION=0ae21984-7c22-4e0d-b12e-e03790fe6ba3; _gat=1; reg_prepareId=17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a; reg_focusId=54c7d421-47a5-4c16-a29d-17491d430a9; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A; user_persistence=bef4f285-6853-4476-bf6e-74cd85552cfa; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1600174444; data-unique-id=8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e; _gat_UA-77727571-3=1; SLARDAR_WEB_ID=09080808-9537-47ce-9745-021db03b845f",
                    "Host": "${host}",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/list",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1600174444",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1599662193,1599875248,1600173818",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "SESSION": "0ae21984-7c22-4e0d-b12e-e03790fe6ba3",
                    "SLARDAR_WEB_ID": "09080808-9537-47ce-9745-021db03b845f",
                    "_ga": "GA1.2.728977736.1599662095",
                    "_gat": "1",
                    "_gat_UA-77727571-3": "1",
                    "_gid": "GA1.2.1134841487.1600173818",
                    "country": "US",
                    "csrf_token": "892e56e3-15a3-46c7-a46d-56476a8e1f69",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "data_unique_id": "d1e44655-5e65-4720-912e-9aece6f1369f",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "reg_focusId": "54c7d421-47a5-4c16-a29d-17491d430a9",
                    "reg_prepareId": "17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a",
                    "s_v_web_id": "kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL",
                    "user_persistence": "bef4f285-6853-4476-bf6e-74cd85552cfa",
                }
            )
            .with_data({"folderId": "0", "keywords": "", "sort": "time", "source": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/message/get_message_unread")
            .post("https://${host}/api/message/get_message_unread")
            .with_headers(
                **{
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Cookie": "_ga=GA1.2.728977736.1599662095; data_unique_id=d1e44655-5e65-4720-912e-9aece6f1369f; mubu_inner=1; csrf_token=892e56e3-15a3-46c7-a46d-56476a8e1f69; s_v_web_id=kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL; reg_entrance=https%3A%2F%2F${host}%2Flist; _gid=GA1.2.1134841487.1600173818; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1599662193,1599875248,1600173818; language=en-US; country=US; SESSION=0ae21984-7c22-4e0d-b12e-e03790fe6ba3; _gat=1; reg_prepareId=17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a; reg_focusId=54c7d421-47a5-4c16-a29d-17491d430a9; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A; user_persistence=bef4f285-6853-4476-bf6e-74cd85552cfa; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1600174444; data-unique-id=8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e; _gat_UA-77727571-3=1; SLARDAR_WEB_ID=09080808-9537-47ce-9745-021db03b845f",
                    "Host": "${host}",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/list",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1600174444",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1599662193,1599875248,1600173818",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "SESSION": "0ae21984-7c22-4e0d-b12e-e03790fe6ba3",
                    "SLARDAR_WEB_ID": "09080808-9537-47ce-9745-021db03b845f",
                    "_ga": "GA1.2.728977736.1599662095",
                    "_gat": "1",
                    "_gat_UA-77727571-3": "1",
                    "_gid": "GA1.2.1134841487.1600173818",
                    "country": "US",
                    "csrf_token": "892e56e3-15a3-46c7-a46d-56476a8e1f69",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "data_unique_id": "d1e44655-5e65-4720-912e-9aece6f1369f",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "reg_focusId": "54c7d421-47a5-4c16-a29d-17491d430a9",
                    "reg_prepareId": "17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a",
                    "s_v_web_id": "kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL",
                    "user_persistence": "bef4f285-6853-4476-bf6e-74cd85552cfa",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/delete_doc")
            .post("https://${host}/api/list/delete_doc")
            .with_headers(
                **{
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Connection": "keep-alive",
                    "Content-Length": "13",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Cookie": "_ga=GA1.2.728977736.1599662095; data_unique_id=d1e44655-5e65-4720-912e-9aece6f1369f; mubu_inner=1; csrf_token=892e56e3-15a3-46c7-a46d-56476a8e1f69; s_v_web_id=kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL; reg_entrance=https%3A%2F%2F${host}%2Flist; _gid=GA1.2.1134841487.1600173818; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1599662193,1599875248,1600173818; language=en-US; country=US; SESSION=0ae21984-7c22-4e0d-b12e-e03790fe6ba3; _gat=1; reg_prepareId=17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a; reg_focusId=54c7d421-47a5-4c16-a29d-17491d430a9; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A; user_persistence=bef4f285-6853-4476-bf6e-74cd85552cfa; data-unique-id=8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e; _gat_UA-77727571-3=1; SLARDAR_WEB_ID=d1c3fe4a-2ef9-4d88-9389-d87660d6aeb9; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1600174456",
                    "Host": "${host}",
                    "Origin": "https://${host}",
                    "Referer": "https://${host}/list",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1600174456",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1599662193,1599875248,1600173818",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiOTAxMDYwOCIsImV4cCI6MTYwMjc2NjQ0MywiaWF0IjoxNjAwMTc0NDQzfQ.VrdTGo1SPaiZ_sOln8uTGIIQwGiYsZJz7QslTrjXWc7DqXb4HproNercy9TxCbSBXtlE8dlft1eX0OpgU6na6A",
                    "SESSION": "0ae21984-7c22-4e0d-b12e-e03790fe6ba3",
                    "SLARDAR_WEB_ID": "d1c3fe4a-2ef9-4d88-9389-d87660d6aeb9",
                    "_ga": "GA1.2.728977736.1599662095",
                    "_gat": "1",
                    "_gat_UA-77727571-3": "1",
                    "_gid": "GA1.2.1134841487.1600173818",
                    "country": "US",
                    "csrf_token": "892e56e3-15a3-46c7-a46d-56476a8e1f69",
                    "data-unique-id": "8a3cc9c0-f752-11ea-b226-ef3ec06d1d1e",
                    "data_unique_id": "d1e44655-5e65-4720-912e-9aece6f1369f",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "reg_focusId": "54c7d421-47a5-4c16-a29d-17491d430a9",
                    "reg_prepareId": "17491d42cdb-17491d42c59-4c16-a29d-314c8a065e9a",
                    "s_v_web_id": "kf3y6bvj_GRvsHTIf_L7Sd_4WvY_9Fuk_K7N6wRZP9hLL",
                    "user_persistence": "bef4f285-6853-4476-bf6e-74cd85552cfa",
                }
            )
            .with_data({"id": "${docId}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
            .assert_equal("body.data", None)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubu().test_start()
